baseURL = 'https://craftedbyjosh.github.io/'
languageCode = 'en-uk'
title = 'CraftedByJosh'
theme = "archie"

copyright = "© CraftedByJosh"
# Code Highlight
# pygmentsstyle = "monokai"
# pygmentscodefences = true
# pygmentscodefencesguesssyntax = true

# disqusShortname = "yourDisqusShortname"

pagination.pagerSize=5 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "A small personal blog about DevOps, Cloud, and Automation by me, Josh. Currently working as a SRE based in the UK."
	mathjax = false # enable MathJax support
	katex = false # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/CraftedByJosh"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/devops-josh"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4